[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap =  { version = "4.5.38", features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }
anyhow = "1.0.98"
solana-client = "=2.2.7"
solana-sdk = "=2.2.2"
sdk = { path = "../sdk" }
