[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client.workspace = true
solana-sdk.workspace = true
anyhow.workspace = true
clap =  { version = "4.5.38", features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }
sdk = { path = "../sdk" }
